DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS findaspot_db;
CREATE DATABASE findaspot_db;



-- DROP DATABASE IF EXISTS testdb;
-- CREATE DATABASE testdb;

DROP DATABASE IF EXISTS parkingSpace_db;
CREATE DATABASE parkingSpace_db;

-- DROP DATABASE IF EXISTS auth_db;
-- CREATE DATABASE auth_db;



